### ISSUE TITLE
加载字体报错, 字体文件不是jar自带的吗?没搞懂咋报错了

### ISSUE THREAD

**Issue by zhyusgethup** [xingyuv/captcha-plus#12]
2024-12-13 15:43:09.417 [main] INFO  c.x.c.s.i.BlockPuzzleCaptchaServiceImpl - --->>>xingyuv captcha-plus 初始化验证码底图<<<---blockPuzzle
2024-12-13 15:43:09.530 [main] ERROR c.x.c.s.i.BlockPuzzleCaptchaServiceImpl - load font error:{}
java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Font.java:1208)
        at java.desktop/java.awt.Font.createFont(Font.java:1076)
        at com.xingyuv.captcha.service.impl.AbstractCaptchaService.loadWaterMarkFont(AbstractCaptchaService.java:210)
        at com.xingyuv.captcha.service.impl.AbstractCaptchaService.init(AbstractCaptchaService.java:100)
      
项目时ruoyi-pro,环境是centos7 jdk17

**Comment by loongw513029** [comment]
yum install -y fontconfig
