### ISSUE TITLE
java.lang.RuntimeException: Fontconfig head is null, check your fonts or fonts configuration

### ISSUE THREAD

**Issue by fanweibin2018** [xingyuv/captcha-plus#8]
环境：jdk21，aliyunlinux3
类型：blockPuzzle
报错日志：
java.lang.RuntimeException: Fontconfig head is null, check your fonts or fonts configuration
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1263)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:221)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:105)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:696)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:352)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:309)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:309)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:55)
	at java.desktop/sun.font.PlatformFontInfo.createFontManager(PlatformFontInfo.java:37)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:51)
	at java.desktop/java.awt.Font.getFont2D(Font.java:526)
	at java.desktop/java.awt.Font$FontAccessImpl.getFont2D(Font.java:265)
	at java.desktop/sun.font.FontUtilities.getFont2D(FontUtilities.java:151)
	at java.desktop/sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:671)
	at java.desktop/sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:837)
	at java.desktop/sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:46)
	at java.desktop/sun.java2d.pipe.ValidatePipe.drawString(ValidatePipe.java:165)
	at java.desktop/sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2931)
	at com.xingyuv.captcha.service.impl.BlockPuzzleCaptchaServiceImpl.get(BlockPuzzleCaptchaServiceImpl.java:65)

**Comment by jpg1024** [comment]
安装一下即可解决:

```
yum install -y fontconfig
```
